version: '3.7'
networks:
  github:
    name: github
    driver: bridge

services:

  php:
    image: likesistemas/php-dev:${PHP_VERSION:-56}
    environment:
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - URL_SENTRY=${URL_SENTRY}
      - DB_HOST=mysql
      - DB_MIGRATE=false
    volumes:
      - ./:/var/www/public/
    networks:
      - github
  
  mysql:
    image: ${DB_ENGINE:-mysql:5.5}
    command: --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./.mysql-data/:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Fortaleza
    networks:
      - github