name: CI

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  
  test:
    strategy:
      matrix:
        PHP: [74, 80, 81, 82, 83]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Up environment
        run: |
          docker compose up -d

      - name: Wait environment
        run: |
          echo $(docker compose -f docker-compose.wait.yml run --rm wait)

      - name: Environment logs
        run: |
          docker compose ps
          docker compose logs php

      - name: Run PHP Unit
        run: |
          docker compose exec -T php composer test

      - name: Run Lint
        run: |
          docker compose exec -T php composer lint

      - name: Run PHP Stan
        run: |
          docker compose exec -T php composer analyse

      - name: Run ECS
        run: |
          docker compose exec -T php composer fix:ci

      - name: Desligando ambiente
        if: ${{ always() }}
        run: |
          docker compose exec -T php rm -Rf vendor/ .env
          docker compose down --remove-orphans